/* CONTRABAND — the catalog (single source of truth for the hub).

   Every entry is a book that is (a) widely taught in U.S. grades 6–12 and
   (b) challenged or removed in U.S. school districts. We index them here as a
   defense of the freedom to read, not as an endorsement of any one edition.

   status:
     "available" — a Contraband/PlotPoint learning room exists → set href
     "building"  — room is planned; copyrighted works are built one at a time
                   with the teacher's own text (paraphrase-only, quotation-free)

   themes (stable keys, translated for display by the hub):
     justice  — Social justice, civil rights, equity
     history  — Actual history & collective memory (Holocaust, slavery, internment)
     identity — Identity, coming of age, DEI, belonging
     power    — Censorship, propaganda, and power itself

   summary — a short, spoiler-light "CliffsNotes-lite" plot line for cards + posters.
   rights  — "public-domain" | "copyrighted"  (copyrighted → companion-only room)
*/
window.CONTRABAND_TITLES = [

  /* ─────────────  GRADES 6–8  ───────────── */
  {
    id: "annefrank",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    year: "1947",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "../activities/plotpoint/annefrank/",
    accent: "#c1272d",
    summary: "A Jewish teenager hiding from the Nazis in a secret annex records two years of fear, hope, and ordinary growing-up in her diary — until the hiding place is discovered.",
    why: "A girl in hiding from the Nazis — challenged for its frank passages on growing up and, absurdly, for being 'a real downer.' The record of the Holocaust told from inside it.",
  },
  {
    id: "rollofthunder",
    title: "Roll of Thunder, Hear My Cry",
    author: "Mildred D. Taylor",
    year: "1976",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "rollofthunder/",
    accent: "#b0472e",
    summary: "In Depression-era Mississippi, nine-year-old Cassie Logan and her family fight to keep their own land and their dignity against the daily cruelties of Jim Crow, as quiet endurance turns into open resistance.",
    why: "A Black family holds onto its land and its dignity in Depression-era Mississippi. Challenged for racial slurs the book depicts to indict them.",
  },
  {
    id: "watsons",
    title: "The Watsons Go to Birmingham — 1963",
    author: "Christopher Paul Curtis",
    year: "1995",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "watsons/",
    accent: "#c9822b",
    summary: "The loving, funny Watson family drives from Michigan to Birmingham, Alabama in 1963 — and arrives just as history turns violent at the 16th Street Baptist Church.",
    why: "A funny, tender family road trip that drives straight into the 16th Street Baptist Church bombing. Challenged over violence and its portrayal of racism.",
  },
  {
    id: "numberthestars",
    title: "Number the Stars",
    author: "Lois Lowry",
    year: "1989",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "numberthestars/",
    accent: "#3a5a8c",
    summary: "In Nazi-occupied Denmark, ten-year-old Annemarie helps her family smuggle her Jewish best friend to safety across the sea — an ordinary girl who finds extraordinary courage.",
    why: "Danish children help smuggle Jewish neighbors to safety. Challenged for Holocaust content deemed too intense — courage under occupation, at a child's eye level.",
  },
  {
    id: "browngirl",
    title: "Brown Girl Dreaming",
    author: "Jacqueline Woodson",
    year: "2014",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "browngirl/",
    accent: "#7a4fce",
    summary: "In lyrical verse, Jacqueline Woodson remembers growing up Black in the 1960s and '70s, between South Carolina and New York, discovering her own voice as a writer.",
    why: "A memoir in verse of growing up Black in the 1960s–70s, between South and North. Challenged for its honest civil-rights history and religion.",
  },
  {
    id: "newkid",
    title: "New Kid",
    author: "Jerry Craft",
    year: "2019",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "newkid/",
    accent: "#d98a2b",
    summary: "Jordan, a Black seventh-grader who loves to draw, is sent to a mostly-white private school far from home and learns to navigate two very different worlds. A funny, honest graphic novel about fitting in.",
    why: "A Newbery-winning graphic novel about a Black seventh-grader at a mostly-white prep school. Pulled from school events over false 'critical race theory' claims.",
  },
  {
    id: "esperanza",
    title: "Esperanza Rising",
    author: "Pam Muñoz Ryan",
    year: "2000",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "esperanza/",
    accent: "#bf5a3a",
    summary: "A wealthy Mexican girl loses everything and must start over as a farm laborer in Depression-era California, discovering resilience, dignity, and solidarity.",
    why: "A wealthy Mexican girl becomes a farmworker in Depression-era California. Challenged over labor organizing, deportation, and class.",
  },
  {
    id: "insideout",
    title: "Inside Out & Back Again",
    author: "Thanhhà Lại",
    year: "2011",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "insideout/",
    accent: "#2f8f8f",
    summary: "Told in verse, ten-year-old Hà flees the fall of Saigon with her family and struggles to rebuild her life — and her sense of self — in Alabama.",
    why: "A verse novel of a girl fleeing the fall of Saigon and remaking herself in Alabama. Challenged over the refugee and war content it exists to teach.",
  },
  {
    id: "ghostboys",
    title: "Ghost Boys",
    author: "Jewell Parker Rhodes",
    year: "2018",
    gradeBand: "6-8",
    grades: "6–8",
    themes: ["justice"],
    rights: "copyrighted",
    status: "available",
    href: "ghostboys/",
    accent: "#4a4f6b",
    summary: "After twelve-year-old Jerome is killed by a police officer who mistook his toy gun for a real one, his ghost witnesses the aftermath and meets the ghost of Emmett Till.",
    why: "A twelve-year-old is killed by police and, as a ghost, meets Emmett Till. Among the most-challenged books in the country over race and policing.",
  },

  /* ─────────────  GRADES 9–12  ───────────── */
  {
    id: "douglass",
    title: "Narrative of the Life of Frederick Douglass",
    author: "Frederick Douglass",
    year: "1845",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "public-domain",
    status: "available",
    href: "douglass/",
    accent: "#6b4f2a",
    sample: true,
    summary: "The most famous of the slave narratives: Frederick Douglass's own account of his life in bondage, his secret path to literacy, and his escape to freedom.",
    why: "A formerly enslaved man's first-person testimony against slavery — long challenged, and exactly the kind of hard history being pulled from shelves. In the public domain and free to read.",
  },
  {
    id: "mockingbird",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    year: "1960",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history"],
    rights: "copyrighted",
    status: "available",
    href: "mockingbird/",
    accent: "#6a7a4a",
    summary: "In a small Alabama town during the Depression, young Scout Finch watches her father, lawyer Atticus Finch, defend a Black man falsely accused of rape. A coming-of-age story about conscience and injustice.",
    why: "The trial of a Black man falsely accused in the Jim Crow South. Perennially challenged for racial slurs — and for making readers sit with injustice.",
  },
  {
    id: "huckfinn",
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    year: "1884",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "public-domain",
    status: "available",
    href: "../activities/plotpoint/huckfinn/",
    accent: "#c1272d",
    summary: "Huck Finn and Jim, a man escaping slavery, raft down the Mississippi River, forging a friendship that defies everything their society taught them.",
    why: "A runaway boy and a man escaping slavery raft down the Mississippi. One of the most-banned books in America — for its language and its indictment of that language's world.",
  },
  {
    id: "night",
    title: "Night",
    author: "Elie Wiesel",
    year: "1960",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history"],
    rights: "copyrighted",
    status: "available",
    href: "night/",
    accent: "#6b6f76",
    summary: "Elie Wiesel's memoir of surviving the Nazi camps of Auschwitz and Buchenwald as a teenager — and of holding onto, and losing, his faith in the darkness.",
    why: "A survivor's memoir of Auschwitz and Buchenwald. Challenged as too dark or too religious — the testimony a Nobel laureate spent his life insisting we not forget.",
  },
  {
    id: "maus",
    title: "Maus: A Survivor's Tale",
    author: "Art Spiegelman",
    year: "1986",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "power"],
    rights: "copyrighted",
    status: "available",
    href: "maus/",
    accent: "#5f5f5f",
    summary: "Art Spiegelman retells his father's survival of the Holocaust as a graphic memoir — Jews drawn as mice, Nazis as cats — while wrestling with his father's memory in the present.",
    why: "A Pulitzer-winning graphic memoir of the Holocaust, mice and cats. Removed by a school board over a few words and a drawing.",
  },
  {
    id: "bluesteye",
    title: "The Bluest Eye",
    author: "Toni Morrison",
    year: "1970",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "bluesteye/",
    accent: "#4a6d8c",
    summary: "In 1940s Ohio, a young Black girl named Pecola, told she is ugly by everyone around her, prays for blue eyes. Toni Morrison's unflinching first novel about beauty, race, and self-worth.",
    why: "A Black girl in 1940s Ohio prays for blue eyes. A Nobel laureate's study of internalized racism — among the most-targeted books in the country.",
  },
  {
    id: "theireyes",
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    year: "1937",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "theireyes/",
    accent: "#8a5a2b",
    summary: "Janie Crawford searches for love and her own voice across three marriages in the Black communities of early-1900s Florida. A landmark of American literature.",
    why: "A Black woman in early-20th-century Florida claims her own voice and desire. Challenged over language and sexuality; a cornerstone of the American canon.",
  },
  {
    id: "cagedbird",
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    year: "1969",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity", "history"],
    rights: "copyrighted",
    status: "available",
    href: "cagedbird/",
    accent: "#9a6b3a",
    summary: "Maya Angelou's memoir of growing up Black and female in the segregated South — surviving trauma and finding strength in words, family, and community.",
    why: "Angelou's memoir of a Black girlhood in the segregated South, including surviving assault. One of the most-banned books of the last 40 years.",
  },
  {
    id: "parttimeindian",
    title: "The Absolutely True Diary of a Part-Time Indian",
    author: "Sherman Alexie",
    year: "2007",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "parttimeindian/",
    accent: "#3a6a5a",
    summary: "Arnold 'Junior' Spirit, a budding cartoonist, leaves his troubled reservation school for an all-white town high school, straddling two worlds. Funny, heartbreaking, and honest.",
    why: "A budget-award memoir-novel of a Spokane teen who transfers to an all-white school. Challenged over language, poverty, and Native experience.",
  },
  {
    id: "hateugive",
    title: "The Hate U Give",
    author: "Angie Thomas",
    year: "2017",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "hateugive/",
    accent: "#b0341f",
    summary: "Sixteen-year-old Starr is the only witness when her unarmed friend is shot by a police officer. Torn between her poor neighborhood and her wealthy school, she has to decide whether to speak out.",
    why: "A teen witnesses a police shooting of her friend and finds her voice. One of the decade's most-challenged books over 'anti-police' and language claims.",
  },
  {
    id: "allamericanboys",
    title: "All American Boys",
    author: "Jason Reynolds & Brendan Kiely",
    year: "2015",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "allamericanboys/",
    accent: "#2f5f9e",
    summary: "After a Black teen is beaten by a white police officer, two boys — the victim and a white classmate who saw it — tell the story from both sides as their town takes sides.",
    why: "Two teens — one Black, one white — reckon with a police beating from both sides. Widely challenged and pulled over race and policing.",
  },
  {
    id: "stamped",
    title: "Stamped: Racism, Antiracism, and You",
    author: "Jason Reynolds & Ibram X. Kendi",
    year: "2020",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "stamped/",
    accent: "#b8231f",
    summary: "A fast, teen-friendly history of racist ideas in America — where they came from, how they persist, and how to be antiracist. Nonfiction that reads like a conversation.",
    why: "A teen 'remix' of the history of racist ideas in America. A lightning rod in book-challenge fights and district removals.",
  },
  {
    id: "justmercy",
    title: "Just Mercy (Adapted for Young Adults)",
    author: "Bryan Stevenson",
    year: "2018",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "power"],
    rights: "copyrighted",
    status: "available",
    href: "justmercy/",
    accent: "#5f6b3a",
    summary: "Lawyer Bryan Stevenson's true account of defending the wrongly condemned — especially Walter McMillian, an innocent man on Alabama's death row — and of mercy in a broken justice system.",
    why: "A lawyer's true account of the wrongly condemned and a broken justice system. Challenged over its portrait of race and the death penalty.",
  },
  {
    id: "mangostreet",
    title: "The House on Mango Street",
    author: "Sandra Cisneros",
    year: "1984",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["identity", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "mangostreet/",
    accent: "#c96b3a",
    summary: "In a series of short, poetic vignettes, a young Latina named Esperanza comes of age on a poor Chicago street and dreams of a house — and a life — of her own.",
    why: "A Latina girl in Chicago writes herself a way out. Challenged over mature vignettes; a staple of American and Mexican-American literature courses.",
  },
  {
    id: "persepolis",
    title: "Persepolis",
    author: "Marjane Satrapi",
    year: "2003",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "power", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "persepolis/",
    accent: "#7a1f2a",
    summary: "In a black-and-white graphic memoir, Marjane Satrapi recalls growing up as a rebellious girl during and after Iran's Islamic Revolution.",
    why: "A graphic memoir of growing up during Iran's revolution. Famously yanked from Chicago classrooms and challenged elsewhere over 'graphic' scenes of state violence.",
  },
  {
    id: "manzanar",
    title: "Farewell to Manzanar",
    author: "Jeanne Wakatsuki Houston & James D. Houston",
    year: "1973",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["history", "justice"],
    rights: "copyrighted",
    status: "available",
    href: "manzanar/",
    accent: "#6a6a55",
    summary: "Jeanne Wakatsuki Houston's memoir of her family's imprisonment at the Manzanar internment camp during World War II, and its lasting effect on their lives.",
    why: "A firsthand account of a Japanese-American family imprisoned in a U.S. internment camp. Challenged for the very history it documents.",
  },
  {
    id: "butterflies",
    title: "In the Time of the Butterflies",
    author: "Julia Alvarez",
    year: "1994",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "power"],
    rights: "copyrighted",
    status: "available",
    href: "../activities/plotpoint/butterflies/",
    accent: "#c1272d",
    summary: "In the Dominican Republic under the Trujillo dictatorship, the four Mirabal sisters join the resistance — and three are murdered for it. Based on a true story.",
    why: "The Mirabal sisters resist a dictatorship in the Dominican Republic — and pay for it. Challenged over violence and politics; a lesson in courage and memory.",
  },
  {
    id: "kindred",
    title: "Kindred",
    author: "Octavia E. Butler",
    year: "1979",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["justice", "history", "identity"],
    rights: "copyrighted",
    status: "available",
    href: "../activities/plotpoint/kindred/",
    accent: "#c1272d",
    summary: "A modern Black woman is repeatedly pulled back in time to an antebellum Maryland plantation, where she must survive slavery to ensure her own family's future.",
    why: "A modern Black woman is pulled back in time to an antebellum plantation. Challenged over its unflinching depiction of slavery's violence.",
  },
  {
    id: "bnw",
    title: "Brave New World",
    author: "Aldous Huxley",
    year: "1932",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "available",
    href: "../activities/plotpoint/bnw/",
    accent: "#c1272d",
    summary: "In a future where people are engineered and drugged into contentment, a few misfits confront what freedom and humanity really cost. Huxley's classic dystopia.",
    why: "An engineered society trades freedom for comfort. Banned and challenged for decades — a book about control that keeps getting controlled.",
  },

  /* ─────────────  Dystopia & censorship  ───────────── */
  {
    id: "fahrenheit451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: "1953",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "building",
    summary: "In a future where firemen start fires to burn books, one fireman begins to wonder what the pages are worth.",
    why: "A novel about burning books that has itself been challenged and censored for decades — the patron saint of any banned-book collection.",
  },
  {
    id: "nineteeneightyfour",
    title: "1984",
    author: "George Orwell",
    year: "1949",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "building",
    summary: "In a totalitarian superstate ruled by Big Brother, Winston Smith commits the ultimate crime: thinking for himself.",
    why: "Surveillance, propaganda, and thought-control. Frequently challenged for its politics and its bleak — and endlessly relevant.",
  },
  {
    id: "animalfarm",
    title: "Animal Farm",
    author: "George Orwell",
    year: "1945",
    gradeBand: "9-12",
    grades: "8–12",
    themes: ["power", "history"],
    rights: "copyrighted",
    status: "building",
    summary: "Farm animals overthrow their farmer to build a society of equals — which slowly curdles into a new tyranny.",
    why: "An allegory of a revolution betrayed. Banned and challenged across the political spectrum for what it exposes about power.",
  },
  {
    id: "handmaidstale",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    year: "1985",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "justice"],
    rights: "copyrighted",
    status: "building",
    summary: "In a near-future theocracy, a woman is reduced to her fertility — and holds onto the memory of the freedom she lost.",
    why: "A dystopia of religious authoritarianism and control over women's bodies. Among the most-challenged books in America.",
  },
  {
    id: "lordoftheflies",
    title: "Lord of the Flies",
    author: "William Golding",
    year: "1954",
    gradeBand: "9-12",
    grades: "9–12",
    themes: ["power"],
    rights: "copyrighted",
    status: "building",
    summary: "Stranded on an island with no adults, a group of schoolboys builds a society that unravels into savagery.",
    why: "Long challenged for violence, bleakness, and language — a fixture of the canon about how thin the veneer of order can be.",
  },
  {
    id: "slaughterhouse",
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    year: "1969",
    gradeBand: "9-12",
    grades: "11–12",
    themes: ["power", "history"],
    rights: "copyrighted",
    status: "building",
    summary: "A dazed WWII veteran comes 'unstuck in time,' reliving the firebombing of Dresden and his abduction by aliens.",
    why: "Anti-war, absurd, and unflinching — one of the most-banned novels in America, once literally burned by a school board.",
  },
];
